#!/usr/bin/env python3
# Copyright (C) 2025-2026 356C LLC
# SPDX-License-Identifier: GPL-3.0-or-later
"""Syntax-check every app translation unit against an older toolchain's headers.

CI's Build job compiles with the runner's own clang, which is newer than every
toolchain the product actually ships on (GCC 8-10 for the AD5M/Pi/K1/K2/CC1
cross builds). A construct clang accepts and an old libstdc++ rejects -
std::from_chars<float>, absent before GCC 11 - can reach main and sit there
until a cross build or a device happens to catch it.

This reuses compile_commands.json (already generated by the native build) and
re-runs each src/ translation unit's own flags through the older compiler with
-fsyntax-only: no codegen, no linking, just "does this parse and resolve
overloads against these headers." It proves nothing about behavior or about
targets other than the one --compiler names.

An explicitly named file absent from compile_commands.json (never built
natively, so there are no flags to borrow) is a FAILURE, not a skip: asking to
check a specific file and getting nothing checked back is exactly the kind of
silent pass this script exists to prevent.

    scripts/check_old_toolchain.py                # every src/ TU, g++-10
    scripts/check_old_toolchain.py --compiler g++-8 src/foo.cpp
"""

import argparse
import json
import os
import pathlib
import shutil
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from merge_compile_commands import entry_argv  # noqa: E402

DB_NAME = "compile_commands.json"
COMPILER_NAMES = {"clang++", "clang", "g++", "gcc", "cc", "c++"}


def rewrite_argv(argv: list[str], compiler: str) -> list[str] | None:
    """Swap the recorded compiler for `compiler`, drop -o, add -fsyntax-only.

    Returns None if no recognizable compiler token is found (a malformed or
    unexpected entry) rather than guessing.
    """
    out: list[str] = []
    replaced = False
    skip_next = False
    for arg in argv:
        if skip_next:
            skip_next = False
            continue
        if arg == "-o":
            skip_next = True
            continue
        if not replaced and arg == "ccache":
            continue
        if not replaced and os.path.basename(arg) in COMPILER_NAMES:
            out.append(compiler)
            replaced = True
            continue
        out.append(arg)
    if not replaced:
        return None
    out.append("-fsyntax-only")
    return out


def check_one(entry: dict, compiler: str, root: pathlib.Path) -> tuple[str, bool, str]:
    rel = os.path.relpath(entry["file"], root)
    argv = rewrite_argv(entry_argv(entry), compiler)
    if argv is None:
        return rel, False, "no recognizable compiler in the recorded command"
    result = subprocess.run(
        argv, cwd=entry.get("directory", str(root)), capture_output=True, text=True, check=False
    )
    return rel, result.returncode == 0, result.stderr


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("files", nargs="*", help="Specific files to check (default: every src/ TU)")
    parser.add_argument("--compiler", default="g++-10", help="Old-toolchain compiler to check against")
    parser.add_argument("--jobs", type=int, default=os.cpu_count() or 4)
    args = parser.parse_args()

    if shutil.which(args.compiler) is None:
        print(f"{args.compiler}: not found on PATH", file=sys.stderr)
        return 2

    root = pathlib.Path(
        subprocess.run(
            ["git", "rev-parse", "--show-toplevel"], capture_output=True, text=True, check=False
        ).stdout.strip()
        or "."
    )
    db_path = root / DB_NAME
    if not db_path.exists():
        print(f"{DB_NAME} not found: run 'make -j' (or a build) first", file=sys.stderr)
        return 2

    db = json.loads(db_path.read_text())
    by_file = {os.path.relpath(e["file"], root): e for e in db}

    # An explicitly named file with no db entry counts as failed, not skipped:
    # a caller asking to check a specific file and getting nothing checked in
    # return is exactly the silent-pass shape this script exists to avoid.
    missing: list[str] = []
    if args.files:
        targets = []
        for f in args.files:
            rel = os.path.relpath(os.path.abspath(f), root)
            entry = by_file.get(rel)
            if entry is None:
                missing.append(rel)
                continue
            targets.append(entry)
    else:
        targets = [e for rel, e in by_file.items() if rel.startswith("src" + os.sep)]

    if not targets and not missing:
        print("no translation units to check - the corpus is empty", file=sys.stderr)
        return 2

    for rel in missing:
        print(f"{rel}: FAILED (no compile_commands.json entry)")

    missing_note = f" ({len(missing)} missing from the database, already reported above)" if missing else ""
    print(f"Checking {len(targets)} translation unit(s) against {args.compiler}...{missing_note}")
    started = time.monotonic()
    failures = len(missing)
    with ThreadPoolExecutor(max_workers=max(1, args.jobs)) as pool:
        for rel, ok, stderr in pool.map(lambda e: check_one(e, args.compiler, root), targets):
            if not ok:
                failures += 1
                print(f"{rel}: FAILED")
                sys.stderr.write(stderr)
    elapsed = time.monotonic() - started

    print(f"summary: {len(targets) + len(missing)} checked, {failures} failed ({elapsed:.1f}s)")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
